#!/usr/bin/env python3
"""Render docker-compose.yml from compose.template.yml by embedding watchdog.py.

Embedding the script as an inline compose config means the stack is a single
file: it deploys from Portainer (web editor or git repository) with nothing to
copy onto the host.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MARKER = "      # @@WATCHDOG_PY@@"


def main():
    script = (ROOT / "watchdog.py").read_text()
    if "$" in script:
        # Compose interpolates dollar signs, even inside config content.
        sys.exit("watchdog.py must not contain '$' characters")
    template = (ROOT / "compose.template.yml").read_text()
    if template.count(MARKER) != 1:
        sys.exit(f"expected exactly one {MARKER.strip()!r} marker in compose.template.yml")
    body = "\n".join(("      " + line) if line else "" for line in script.splitlines())
    header = "# DO NOT EDIT: generated by render_compose.py from compose.template.yml + watchdog.py\n"
    (ROOT / "docker-compose.yml").write_text(header + template.replace(MARKER, body))
    print("wrote docker-compose.yml")


if __name__ == "__main__":
    main()
